deploymentName: doodle-repository-deployment
deploymentLabel: doodle-repository

replicaCount: 1

image:
  repository: mysql
  tag: 8.0.29

containerPort: 3307

service:
  type: ClusterIP
  port: 3308
  targetPort: 3308

config_enabled: false
zipkin_enabled: false
profile_enabled: false
application_name_enabled: false
encrypt_enabled: false
is_database: true

root_password: rootpassword1234
database: doodle
user: doodle
password: doodlePassword1234
tcp_port: 3308