deploymentName: gateway-deployment
deploymentLabel: gateway

replicaCount: 1

image:
  repository: ruldarm00/eku-gateway
  tag: latest

containerPort: 8073

service:
  type: LoadBalancer
  port: 8073
  targetPort: 8080

config_enabled: true
zipkin_enabled: true
profile_enabled: true
application_name_enabled: true
encrypt_enabled: false
is_database: false

application_name: gateway