version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper
    networks:
      - eku
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    depends_on:
      - zookeeper
    networks:
      - eku
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092, PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092

  zipkin:
    image: openzipkin/zipkin
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "9411:9411"
    networks:
      - eku

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    ports:
      - "8073:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev

  configserver:
    image: ruldarm00/eku-configserver
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8071:8071"
    depends_on:
      - zipkin
      - kafka
    networks:
      - eku
    environment:
      SERVER_PORT: 8071
      SPRING_PROFILES_ACTIVE: git
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/hyeonho9877/EKU-config.git
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT-LABEL: main
      ENCRYPT_KEY: ddldddtkqslkxhddogkcrgnriklkurfqlstdsndqdkqnlrsdelrmfsdgdgkrdlwlsfhlnkdssjstmfqrrnalqfmsfwniksrPoruodgfrvdjtlkkhsldlnhghkavkceeiorkr
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  eurekaserver:
    image: ruldarm00/eureka
    ports:
      - "8070:8070"
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    networks:
      - eku
    depends_on:
      - configserver
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

#  critic-repository:
#    image: mysql:8.0.29
#    ports:
#      - "3307:3307"
#    networks:
#      - eku
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    environment:
#      MYSQL_ROOT_PASSWORD: "inthegardenofsinners"
#      MYSQL_DATABASE: critic
#      MYSQL_USER: critic
#      MYSQL_PASSWORD: criticPassword1234
#      MYSQL_TCP_PORT: 3307
#    volumes:
#      - /etc/docker/critic/mysql/data:/var/lib/mysql
#
#  critic:
#    image: ruldarm00/eku-critic
#    ports:
#      - "8080:8080"
#    networks:
#      - eku
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#      restart_policy:
#        condition: on-failure
#        delay: 30s
#        max_attempts: 3
#        window: 120s
#    depends_on:
#      - eurekaserver
#      - critic-repository
#    environment:
#      SPRING_APPLICATION_NAME: critic
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
#
#  doodle-repository:
#    image: mysql:8.0.29
#    ports:
#      - "3308:3308"
#    networks:
#      - eku
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    environment:
#      MYSQL_ROOT_PASSWORD: "inthegardenofsinners"
#      MYSQL_DATABASE: doodle
#      MYSQL_USER: doodle
#      MYSQL_PASSWORD: doodlePassword1234
#      MYSQL_TCP_PORT: 3308
#    volumes:
#      - /etc/docker/doodle/mysql/data:/var/lib/mysql
#
#  doodle:
#    image: ruldarm00/eku-doodle
#    ports:
#      - "8081:8080"
#    networks:
#      - eku
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#      restart_policy:
#        condition: on-failure
#        delay: 30s
#        max_attempts: 3
#        window: 120s
#    depends_on:
#      - eurekaserver
#      - doodle-repository
#    environment:
#      SPRING_APPLICATION_NAME: doodle
#      SPRING_PROFILES_ACTIVE: dev
#      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  freeboard-repository:
    image: mysql:8.0.29
    ports:
      - "3309:3309"
    networks:
      - eku
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      MYSQL_ROOT_PASSWORD: "inthegardenofsinners"
      MYSQL_DATABASE: freeboard
      MYSQL_USER: freeboard
      MYSQL_PASSWORD: freeboardPassword1234
      MYSQL_TCP_PORT: 3309
    volumes:
      - /etc/docker/freeboard/mysql/data:/var/lib/mysql

  freeboard:
    image: ruldarm00/eku-freeboard
    ports:
      - "8082:8080"
    networks:
      - eku
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    depends_on:
      - eurekaserver
      - freeboard-repository
    environment:
      SPRING_APPLICATION_NAME: freeboard
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/



networks:
  eku: