deploymentName: critic-deployment
deploymentLabel: critic

replicaCount: 1

image:
  repository: ruldarm00/eku-critic
  tag: latest

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

config_enabled: true
zipkin_enabled: true
profile_enabled: true
application_name_enabled: true
encrypt_enabled: false
is_database: false

application_name: critic