deploymentName: account-deployment
deploymentLabel: account

replicaCount: 1

image:
  repository: ruldarm00/eku-account
  tag: latest

containerPort: 8084

service:
  type: ClusterIP
  port: 8084
  targetPort: 8080

config_enabled: true
zipkin_enabled: true
profile_enabled: true
application_name_enabled: true
encrypt_enabled: false
is_database: false

application_name: account