apiVersion: v2
name: stage
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: eku-common
    version: 0.1.0
    repository: file://../../eku-common/
  - name: zipkin
    version: 0.1.0
    repository: file://../../eku-services/zipkin
  - name: configserver
    version: 0.1.0
    repository: file://../../eku-services/configserver
  - name: eurekaserver
    version: 0.1.0
    repository: file://../../eku-services/eurekaserver
  - name: account
    version: 0.1.0
    repository: file://../../eku-services/account
  - name: critic
    version: 0.1.0
    repository: file://../../eku-services/critic
  - name: critic-repository
    version: 0.1.0
    repository: file://../../eku-services/critic-repository
  - name: infoboard
    version: 0.1.0
    repository: file://../../eku-services/infoboard
#  - name: infoboard-repository
#    version: 0.1.0
#    repository: file://../../eku-services/infoboard-repository
  - name: freeboard
    version: 0.1.0
    repository: file://../../eku-services/freeboard
#  - name: freeboard-repository
#    version: 0.1.0
#    repository: file://../../eku-services/freeboard-repository
  - name: doodle
    version: 0.1.0
    repository: file://../../eku-services/doodle
#  - name: doodle-repository
#    version: 0.1.0
#    repository: file://../../eku-services/doodle-repository
  - name: gatewayserver
    version: 0.1.0
    repository: file://../../eku-services/gatewayserver