deploymentName: freeboard-deployment
deploymentLabel: freeboard

replicaCount: 1

image:
  repository: ruldarm00/eku-freeboard
  tag: latest

containerPort: 8082

service:
  type: ClusterIP
  port: 8082
  targetPort: 8080

config_enabled: true
zipkin_enabled: true
profile_enabled: true
application_name_enabled: true
encrypt_enabled: false
is_database: false

application_name: freeboard