deploymentName: eurekaserver-deployment
deploymentLabel: eurekaserver

replicaCount: 1

image:
  repository: ruldarm00/eku-eureka
  tag: latest

containerPort: 8070

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070

application_name_enabled: true
config_enabled: true
zipkin_enabled: true
profile_enabled: true
encrypt_enabled: false
is_database: false

application_name: eurekaserver