deploymentName: zipkin-deployment
deploymentLabel: zipkin

replicaCount: 1

image:
  repository: openzipkin/zipkin
  tag: latest

containerPort: 9411

service:
  type: ClusterIP
  port: 9411
  targetPort: 9411

application_name_enabled: false
config_enabled: false
zipkin_enabled: false
profile_enabled: false
encrypt_enabled: false
is_database: false